name: bloc_ecommerce
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

#--------------- Packages ------------#
dependencies:
  flutter:
    sdk: flutter


  # Utility Packages
  http: ^1.1.0
  intl: ^0.19.0
  flutter_svg: ^2.0.10+1


  # Images
  lottie: ^2.6.0
  shimmer: ^3.0.0
  image_picker: ^1.1.0
  shadow_overlay: ^1.0.5

  #icons
  cupertino_icons: ^1.0.2

  # State Management
  flutter_bloc: ^8.1.6
  get_it: ^8.0.0
  dartz: ^0.10.1

  # Network
  dio: ^5.4.3+1
  cached_network_image: ^3.3.1
  connectivity_plus: ^5.0.2



  # Firebase and Google Maps
  firebase_core: ^2.24.2
  firebase_auth: ^4.14.0
  cloud_firestore: ^4.13.1

  #---------------- ./Packages END -------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logos/appLogo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: true
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "path/to/image.png"


flutter:
  uses-material-design: true

  #---------------- LOCAL ASSETS -------------#
  assets:
    - assets/fonts/
    - assets/images/
    - assets/vectors/


  #---------------- LOCAL FONTS -------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800






